services:
  nats-service:
    image: nats:latest
    ports:
      - 8222:8222
  client-gateway:
    build: 
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/microservices-nestjs-450117/image-registry/client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-service:4222

  products-ms:
    build: 
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/microservices-nestjs-450117/image-registry/products-ms
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-service:4222
      - DATABASE_URL=file:./dev.db

  orders-ms:
    build: 
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: northamerica-south1-docker.pkg.dev/microservices-nestjs-450117/image-registry/orders-ms
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-service:4222
      - DATABASE_URL=${ORDERS_DATABASE_URL}

  payments-ms:
    build: 
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/microservices-nestjs-450117/image-registry/payments-ms
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-service:4222
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - SUCCESS_URL=${SUCCESS_URL}
      - CANCEL_URL=${CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}

  auth-ms:
    build: 
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/microservices-nestjs-450117/image-registry/auth-ms
    environment:
      - NATS_SERVERS=nats://nats-service:4222
      - PORT=${AUTH_MS_PORT}
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
